Review profiles operated by 21Vianet
iterate-ch/profiles pull request #57
Opened 2023-08-11 09:55 UTC by dkocher

2023-08-11 09:56 UTC, dkocher commented
- [ ] Depends on iterate-ch/cyberduck#14877.
- [ ] Depends on iterate-ch/cyberduck#14978.

2023-08-14 08:13 UTC, AliveDevil requested changes

2023-08-16 11:01 UTC, AliveDevil requested changes

2023-08-16 11:01 UTC, AliveDevil commented on Microsoft 365 China Sharepoint.cyberduckprofile
> +        <string>${oauth.handler.scheme}://oauth</string>
Missing then for Sharepoint Site-profile.

2023-10-05 15:16 UTC, merged