New DigitalOcean Spaces Profiles
iterate-ch/profiles pull request #60
Opened 2023-08-20 20:58 UTC by jbraunstein-do

2023-08-21 19:53 UTC, dkocher requested changes

2023-08-21 19:53 UTC, dkocher commented on DigitalOcean Spaces (blr1).cyberduckprofile
> +        <string>https://trac.cyberduck.io/wiki/help/en/howto/digitalocean</string>
Please change to the redirect target `https://docs.cyberduck.io/protocols/s3/digitalocean/`

```suggestion
        <string>https://docs.cyberduck.io/protocols/s3/digitalocean/</string>
```

2023-08-21 19:53 UTC, dkocher commented on DigitalOcean Spaces (syd1).cyberduckprofile
> +        <string>https://trac.cyberduck.io/wiki/help/en/howto/digitalocean</string>
Please change to the redirect target `https://docs.cyberduck.io/protocols/s3/digitalocean/`

```suggestion
        <string>https://docs.cyberduck.io/protocols/s3/digitalocean/</string>
```

2023-08-21 19:53 UTC, dkocher commented on DigitalOcean Spaces (sfo3).cyberduckprofile
>  <?xml version="1.0" encoding="UTF-8"?>
Can be omitted in this changeset.

2023-08-21 20:54 UTC, dkocher approved these changes

2023-08-22 06:32 UTC, merged

2023-08-23 12:01 UTC, dkocher commented
@jbraunstein-do  It would be great if you can open an additional pull request in docs [^1] to update the [documentation](https://docs.cyberduck.io/protocols/s3/digitalocean/).

[^1]: https://github.com/iterate-ch/docs

2023-08-23 19:36 UTC, jbraunstein-do commented
Done, thank you. https://github.com/iterate-ch/docs/pull/404

On Wed, Aug 23, 2023 at 5:01 AM David Kocher ***@***.***>
wrote:

> @jbraunstein-do <https://github.com/jbraunstein-do> It would be great if
> you can open an additional pull request in docs 1
> <#m_3885267427002209444_user-content-fn-1-6d473b320d8e7afc6c0c2f5644949ce9>
> to update the documentation
> <https://docs.cyberduck.io/protocols/s3/digitalocean/>.
> Footnotes
>
>    1.
>
>    https://github.com/iterate-ch/docs ↩
>    <#m_3885267427002209444_user-content-fnref-1-6d473b320d8e7afc6c0c2f5644949ce9>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/iterate-ch/profiles/pull/60#issuecomment-1689836018>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AWOWDXTBRUY2OFSAIXZXOM3XWXWKTANCNFSM6AAAAAA3XQLCNY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>